(WIP) Handle 406 errors apart from generic Carina errors
rackerlabs/libcarina pull request #22
Opened 2016-12-12 20:51 UTC by thomasem

2016-12-12 21:55 UTC, carolynvs commented
Looks good, have a 👍 after you get a ✅

2016-12-14 22:35 UTC, thomasem commented
@carolynvs Ready for final review.

2016-12-14 22:44 UTC, carolynvs requested changes

2016-12-14 22:44 UTC, carolynvs commented on libcarina_test.go
> +func TestMicroversionUnsupportedNewRequest(t *testing.T) {
Is this still needed now that we have tests on get/list/etc?

2016-12-14 22:44 UTC, carolynvs commented on libcarina_test.go
> +func TestMicroversionUnsupportedGetAPIMetadata(t *testing.T) {
I would lean towards removing this as part of the story, since it's not used anymore.

2016-12-14 22:48 UTC, thomasem commented on libcarina_test.go
> +func TestMicroversionUnsupportedGetAPIMetadata(t *testing.T) {
It still represents bindings for a particular portion of the API. Are you suggesting I delete the function from the library?

2016-12-14 22:50 UTC, thomasem commented on libcarina_test.go
> +func TestMicroversionUnsupportedNewRequest(t *testing.T) {
I think it's some extra assurance about all things calling the Carina API. Sort of asserts that the expectations of `NewRequest` for other functions that're using it. That way you can tell, if you start seeing failures, whether it's in `NewRequest`, or something calling it.

2016-12-14 22:52 UTC, carolynvs commented on libcarina_test.go
> +func TestMicroversionUnsupportedNewRequest(t *testing.T) {
A+, makes sense to me

2016-12-14 22:53 UTC, carolynvs commented on libcarina_test.go
> +func TestMicroversionUnsupportedGetAPIMetadata(t *testing.T) {
Yeah, it was always the plan to nuke that when we had the 406 responses out of the API.

2016-12-14 22:58 UTC, thomasem commented on libcarina_test.go
> +func TestMicroversionUnsupportedGetAPIMetadata(t *testing.T) {
Fixed

2016-12-14 22:58 UTC, carolynvs approved these changes

2016-12-14 22:59 UTC, carolynvs commented
:shipit:

2016-12-14 22:59 UTC, merged